// Danh sach tu tieng Viet khong dau, dung de tao passphrase de nho.
// Chi gom cac am tiet ngan, de doc, de go tren ban phim US.
pub const WORDS: &[&str] = &[
    "an", "anh", "ao", "bac", "bach", "bai", "ban", "bang", "banh", "bao", "bat", "bay", "be",
    "ben", "beo", "bien", "biet", "binh", "bo", "boi", "bong", "bot", "buoc", "buom", "buon",
    "but", "ca", "cac", "cach", "cai", "cam", "can", "cang", "canh", "cao", "cat", "cau", "cay",
    "che", "chi", "chia", "chien", "chim", "chin", "chinh", "cho", "choi", "chua", "chuan",
    "chung", "chuoi", "chuot", "co", "coc", "com", "con", "cong", "cua", "cuc", "cung", "cuoi",
    "cuop", "da", "dai", "dam", "dan", "dang", "danh", "dao", "dat", "dau", "day", "de", "dem",
    "den", "deo", "dep", "di", "dia", "diem", "dien", "dieu", "dinh", "do", "doan", "doc", "doi",
    "dom", "don", "dong", "du", "dua", "duc", "dung", "duoi", "duong", "gac", "gai", "gan", "gang",
    "gao", "gap", "gat", "gau", "gay", "ghe", "ghi", "gia", "giai", "giam", "gian", "giang",
    "giao", "gio", "giong", "goc", "goi", "gon", "gong", "gung", "ha", "hai", "ham", "han", "hang",
    "hanh", "hao", "hat", "hau", "hay", "he", "hen", "heo", "hiem", "hien", "hieu", "ho", "hoa",
    "hoc", "hoi", "hom", "hon", "hong", "hop", "hu", "hue", "hung", "huong", "huyen", "keo",
    "khac", "khai", "kham", "khan", "khe", "khi", "kho", "khoa", "khoe", "khong", "khu", "kien",
    "kim", "kinh", "la", "lac", "lai", "lam", "lan", "lang", "lanh", "lao", "lat", "lau", "le",
    "len", "leo", "lich", "lien", "lieu", "linh", "lo", "loa", "loai", "loc", "loi", "lon", "long",
    "lua", "luan", "luc", "lung", "luoi", "luong", "ly", "ma", "mac", "mai", "mam", "man", "mang",
    "manh", "mao", "mat", "mau", "may", "me", "men", "meo", "mien", "minh", "mo", "moc", "moi",
    "mon", "mong", "mua", "muc", "mui", "muoi", "muon", "my", "na", "nam", "nan", "nang", "nao",
    "nap", "nau", "nay", "nem", "nen", "neo", "net", "ngan", "ngang", "nghe", "nghi", "ngoc",
    "ngoi", "ngon", "ngu", "nguoi", "nguon", "nha", "nhac", "nhai", "nham", "nhan", "nhanh",
    "nhat", "nhi", "nho", "nhu", "nhung", "nien", "no", "noi", "non", "nong", "nui", "nuoc", "oai",
    "oc", "ong", "pha", "phai", "pham", "phan", "phao", "phat", "phi", "phim", "pho", "phong",
    "phu", "phuc", "phuong", "qua", "quan", "quang", "que", "quen", "qui", "quoc", "ra", "rac",
    "rang", "ranh", "rau", "re", "reo", "rieng", "rong", "ruoi", "ruong", "sa", "sac", "sai",
    "sam", "san", "sang", "sao", "sat", "sau", "say", "se", "sen", "sinh", "so", "soi", "son",
    "song", "suoi", "ta", "tac", "tai", "tam", "tan", "tang", "tao", "tap", "tau", "tay", "te",
    "tem", "ten", "thai", "tham", "than", "thang", "thanh", "thao", "the", "them", "theo", "thi",
    "thich", "thien", "thiet", "tho", "thoi", "thong", "thu", "thuan", "thuc", "thuy", "tich",
    "tien", "tiep", "tiet", "tim", "tin", "tinh", "to", "toa", "toan", "toi", "tom", "ton", "tong",
    "tra", "trai", "tram", "tran", "trang", "tranh", "treo", "tri", "trong", "truc", "trung",
    "truong", "tu", "tuan", "tuc", "tui", "tuoi", "tuong", "tuyet", "uoc", "van", "vang", "vao",
    "vat", "ve", "ven", "vi", "viec", "vien", "viet", "vinh", "vo", "voi", "von", "vong", "vua",
    "vui", "vuon", "xa", "xanh", "xay", "xe", "xem", "xin", "xoai", "xom", "xuan", "xuong", "yen",
];
